runtime: python38

instance_class: F2

handlers:
- url: /admin/.*
  script: admin.app

- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "feme_core.settings"

automatic_scaling:
  target_cpu_utilization: 0.65 

vpc_access_connector:
  name: projects/devops-feme/locations/us-central1/connectors/feme-router
  egress_setting: all-traffic