version: "3.8"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/feme-core
    ports:
      - "8000:8000"
