version: "3.8"

services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/manage.py runserver 0.0.0.0:$PORT
    volumes:
      - .:/feme-core
    ports:
      - "$PORT:$PORT"
