version: "3.8"

services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/manage.py runserver 0.0.0.0:8080
    environment:
      - DEBUG=1
    volumes:
      - .:/feme-core
    image: feme-core-web
    ports:
      - "8080:8080"
