# Generated by Django 4.2 on 2023-06-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColeTabla',
            fields=[
                ('uuid_cole', models.TextField(blank=True, db_column='uuid_cole', primary_key=True, serialize=False)),
                ('colegio', models.TextField(blank=True, null=True)),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('zona_horaria', models.TextField(blank=True, null=True)),
                ('sexo_colegio', models.TextField(blank=True, db_column='sexo_colegio', null=True)),
                ('zoho_link', models.TextField(blank=True, db_column='zoho_link_', null=True)),
            ],
            options={
                'db_table': 'colegio_tabla',
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_mol', models.TextField(blank=True, db_column='id_mol', primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulos',
            },
        ),
        migrations.CreateModel(
            name='MonitorTabla',
            fields=[
                ('uuid_mont', models.TextField(blank=True, db_column='uuid_mont', primary_key=True, serialize=False)),
                ('monitor', models.TextField(blank=True, null=True)),
                ('materia_feme', models.TextField(blank=True, null=True)),
                ('field_puntaje', models.FloatField(blank=True, db_column='per_puntaje', null=True)),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email_m', models.TextField(blank=True, null=True)),
                ('id_thinki_mon', models.FloatField(blank=True, null=True)),
                ('userToken', models.CharField(blank=True, db_column='userToken', max_length=100, null=True, unique=True)),
                ('uuid_cole', models.ForeignKey(db_column='uuid_cole', on_delete=django.db.models.deletion.CASCADE, to='core.coletabla')),
            ],
            options={
                'db_table': 'monitor_tabla',
            },
        ),
        migrations.CreateModel(
            name='SalonTabla',
            fields=[
                ('uuid_salon', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('cierre_definitivo', models.DateField(blank=True, db_column='cierre_definitivo', null=True)),
                ('l3_22_23', models.TextField(blank=True, db_column='l3_22_23', null=True)),
                ('l3_22_23_2', models.TextField(blank=True, db_column='l3_22_23_2', null=True)),
                ('l3_22_23_au', models.TextField(blank=True, db_column='l3_22_23_au', null=True)),
                ('id_monitor', models.ForeignKey(db_column='uuid_mont', on_delete=django.db.models.deletion.CASCADE, to='core.monitortabla')),
            ],
            options={
                'db_table': 'salon_tabla',
            },
        ),
        migrations.CreateModel(
            name='SalonKpiModulo',
            fields=[
                ('id_skm', models.IntegerField(db_column='id_skm', primary_key=True, serialize=False, unique=True)),
                ('grado', models.TextField(blank=True, null=True)),
                ('seccion', models.TextField(blank=True, null=True)),
                ('modulo', models.TextField(blank=True, null=True)),
                ('total_estudiantes', models.IntegerField(blank=True, db_column='total_estudiantes', null=True)),
                ('iniciaron', models.IntegerField(blank=True, null=True)),
                ('llevan50', models.IntegerField(blank=True, db_column='llevan_50', null=True)),
                ('completaron', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id_mol', models.ForeignKey(db_column='id_mol', on_delete=django.db.models.deletion.CASCADE, to='core.modulos')),
                ('uuid_salon', models.ForeignKey(db_column='uuid_salon', on_delete=django.db.models.deletion.CASCADE, to='core.salontabla')),
            ],
            options={
                'db_table': 'salon_kpi_modulo',
            },
        ),
        migrations.CreateModel(
            name='QuizTabla',
            fields=[
                ('id_q', models.IntegerField(db_column='id_q', primary_key=True, serialize=False, unique=True)),
                ('id_pregunta', models.TextField(blank=True, db_column='id_pregunta', null=True)),
                ('quiz', models.IntegerField(blank=True, null=True)),
                ('seccion', models.IntegerField(blank=True, null=True)),
                ('titulo_de_seccion', models.TextField(blank=True, null=True)),
                ('pregunta', models.TextField(blank=True, null=True)),
                ('respuesta_correcta', models.TextField(blank=True, null=True)),
                ('respuesta_incorrecta_1', models.TextField(blank=True, null=True)),
                ('respuesta_incorrecta_2', models.TextField(blank=True, null=True)),
                ('respuesta_incorrecta_3', models.TextField(blank=True, null=True)),
                ('respuesta_incorrecta_4', models.TextField(blank=True, null=True)),
                ('explicacion_de_la_respueta_correcta', models.TextField(blank=True, db_column='explicacion_correcta', null=True)),
                ('id_mol', models.ForeignKey(db_column='id_mol', on_delete=django.db.models.deletion.CASCADE, to='core.modulos')),
            ],
            options={
                'db_table': 'quiz_tabla',
            },
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id_m', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tiempo_sesion', models.IntegerField(blank=True, null=True)),
                ('sign_in', models.TimeField(blank=True, null=True)),
                ('sign_out', models.TimeField(blank=True, null=True)),
                ('dia', models.DateField(blank=True, null=True)),
                ('id_thinki_mon', models.ForeignKey(db_column='id_thinki_mon', on_delete=django.db.models.deletion.CASCADE, to='core.monitortabla')),
            ],
            options={
                'db_table': 'monitoreo',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_f', models.IntegerField(primary_key=True, serialize=False)),
                ('feedback', models.TextField(blank=True, db_column='feedback', null=True)),
                ('errores', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('id_thinki_mon', models.ForeignKey(db_column='id_thinki_mon', on_delete=django.db.models.deletion.CASCADE, to='core.monitortabla')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='EstudiantesTabla',
            fields=[
                ('id_thinkific', models.IntegerField(blank=True, db_column='id_thinkific', primary_key=True, serialize=False)),
                ('uuid_salon', models.TextField(blank=True, null=True)),
                ('colegio', models.TextField(blank=True, null=True)),
                ('grado', models.TextField(blank=True, null=True)),
                ('seccion', models.TextField(blank=True, null=True)),
                ('nombres_estudiantes', models.TextField(blank=True, null=True)),
                ('apellidos_estudiantes', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('whatsapp_estudiante', models.IntegerField(blank=True, null=True)),
                ('nombres_representante', models.TextField(blank=True, null=True)),
                ('apellidos_representante', models.TextField(blank=True, null=True)),
                ('whatsapp_representante', models.IntegerField(blank=True, null=True)),
                ('email_representante', models.TextField(blank=True, null=True)),
                ('inscrito', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid_cole', models.ForeignKey(db_column='uuid_cole', on_delete=django.db.models.deletion.CASCADE, to='core.coletabla')),
                ('uuid_mont', models.ForeignKey(db_column='uuid_mont', on_delete=django.db.models.deletion.CASCADE, to='core.monitortabla')),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id_s', models.IntegerField(db_column='id_s', primary_key=True, serialize=False, unique=True)),
                ('modulo', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, db_column='email', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expirated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('per_completation', models.IntegerField(blank=True, null=True)),
                ('per_videos', models.IntegerField(blank=True, null=True)),
                ('estatus', models.TextField(blank=True, db_column='estatus', null=True)),
                ('created_at', models.DateTimeField()),
                ('last_sign_in', models.DateTimeField(blank=True, null=True)),
                ('nota_quiz1', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('nota_quiz2', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('nota_quiz3', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('fecha_q1', models.DateTimeField(blank=True, null=True)),
                ('fecha_q2', models.DateTimeField(blank=True, null=True)),
                ('fecha_q3', models.DateTimeField(blank=True, null=True)),
                ('nota_quizes', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('nota_progreso', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('nota_total', models.IntegerField(blank=True, null=True)),
                ('nota_total_l', models.TextField(blank=True, db_column='nota_total_l', null=True)),
                ('id_thinkific', models.ForeignKey(db_column='id_thinkific', on_delete=django.db.models.deletion.CASCADE, to='core.estudiantestabla')),
            ],
            options={
                'db_table': 'estatus',
            },
        ),
    ]
