# Generated by Django 4.2 on 2023-07-12 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColegioTabla',
            fields=[
                ('uuid_cole', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('colegio', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('zona_horaria', models.CharField(max_length=255)),
                ('sexo_colegio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'colegio_tabla',
            },
        ),
        migrations.CreateModel(
            name='ModuloContenido',
            fields=[
                ('id_cont', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('orden', models.IntegerField()),
                ('contenido', models.CharField(max_length=255)),
                ('semana_recom', models.IntegerField()),
                ('tipo', models.IntegerField()),
            ],
            options={
                'db_table': 'modulo_contenido',
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_mol', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modulos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('permisos', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='SalonTabla',
            fields=[
                ('uuid_salon', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('cierre_definitivo', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('per_puntaje', models.IntegerField(null=True)),
                ('materia_feme', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'salon_tabla',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_v', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('colegio', models.CharField(max_length=255)),
                ('grado', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('whatsapp', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('inscrito', models.CharField(max_length=2)),
                ('rol', models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
                ('uuid_cole', models.ForeignKey(db_column='uuid_cole', on_delete=django.db.models.deletion.CASCADE, to='core.colegiotabla')),
                ('uuid_salon', models.ForeignKey(db_column='uuid_salon', on_delete=django.db.models.deletion.CASCADE, to='core.salontabla')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ValuThinkific',
            fields=[
                ('id_thinkific', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_v', models.ForeignKey(db_column='id_v', on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
            options={
                'db_table': 'valu_thinkific',
            },
        ),
        migrations.CreateModel(
            name='QuizTabla',
            fields=[
                ('id_q', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_pregunta', models.CharField(max_length=255)),
                ('quiz', models.IntegerField()),
                ('seccion', models.IntegerField()),
                ('titulo_de_seccion', models.CharField(max_length=255)),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta_correcta', models.CharField(max_length=255)),
                ('respuesta_incorrecta_1', models.CharField(max_length=255)),
                ('respuesta_incorrecta_2', models.CharField(max_length=255)),
                ('respuesta_incorrecta_3', models.CharField(max_length=255)),
                ('respuesta_incorrecta_4', models.CharField(max_length=255)),
                ('explicacion_correcta', models.CharField(max_length=255)),
                ('id_cont', models.ForeignKey(db_column='id_cont', on_delete=django.db.models.deletion.CASCADE, to='core.modulocontenido')),
            ],
            options={
                'db_table': 'quiz_tabla',
            },
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id_m', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tiempo_sesion', models.IntegerField()),
                ('sign_out', models.DateTimeField()),
                ('sign_in', models.DateTimeField()),
                ('dia', models.DateField()),
                ('id_v', models.ForeignKey(db_column='id_v', on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
            options={
                'db_table': 'monitoreo',
            },
        ),
        migrations.AddField(
            model_name='modulocontenido',
            name='id_mol',
            field=models.ForeignKey(db_column='id_mol', on_delete=django.db.models.deletion.CASCADE, to='core.modulos'),
        ),
        migrations.CreateModel(
            name='Jerarquium',
            fields=[
                ('id_j', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_coordinador', models.IntegerField(null=True)),
                ('id_profe', models.IntegerField(null=True)),
                ('id_representante', models.IntegerField(null=True)),
                ('id_estudiante', models.ForeignKey(db_column='id_v', on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
            options={
                'db_table': 'jerarquia',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_f', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('feedback', models.CharField(max_length=255)),
                ('errores', models.CharField(max_length=255)),
                ('id_v', models.ForeignKey(db_column='id_v', on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='EstatusValu',
            fields=[
                ('id_ev', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('modulo', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expirated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('per_completacion', models.IntegerField()),
                ('per_videos', models.IntegerField()),
                ('estatus', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('last_sign_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota_quiz1', models.FloatField()),
                ('intento_quiz1', models.IntegerField()),
                ('nota_quiz2', models.FloatField()),
                ('intento_quiz2', models.IntegerField()),
                ('nota_quiz3', models.FloatField()),
                ('intento_quiz3', models.IntegerField()),
                ('fecha_q1', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_q2', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_q3', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota_total', models.IntegerField()),
                ('nota_total_l', models.CharField(max_length=255)),
                ('id_v', models.ForeignKey(db_column='id_v', on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
            options={
                'db_table': 'estatus_valu',
            },
        ),
        migrations.CreateModel(
            name='EstatusThinkific',
            fields=[
                ('id_t', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('modulo', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expirated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('per_completacion', models.IntegerField()),
                ('per_videos', models.IntegerField()),
                ('estatus', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sign_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota_quiz1', models.FloatField(null=True)),
                ('nota_quiz2', models.FloatField(null=True)),
                ('nota_quiz3', models.FloatField(null=True)),
                ('fecha_q1', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_q2', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_q3', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota_quizes', models.FloatField()),
                ('nota_progreso', models.FloatField()),
                ('nota_total', models.IntegerField()),
                ('nota_total_l', models.CharField(max_length=255)),
                ('id_thinkific', models.ForeignKey(db_column='id_thinkific', on_delete=django.db.models.deletion.CASCADE, to='core.valuthinkific')),
            ],
            options={
                'db_table': 'estatus_thinkific',
            },
        ),
        migrations.CreateModel(
            name='ContenidosColegio',
            fields=[
                ('id_c', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('lapso', models.IntegerField()),
                ('id_mol', models.ForeignKey(db_column='id_mol', on_delete=django.db.models.deletion.CASCADE, to='core.modulos')),
                ('uuid_salon', models.ForeignKey(db_column='uuid_salon', on_delete=django.db.models.deletion.CASCADE, to='core.salontabla')),
            ],
            options={
                'db_table': 'contenidos_colegio',
            },
        ),
    ]
