# Generated by Django 4.2 on 2023-04-24 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColeTabla',
            fields=[
                ('uuid_cole', models.TextField(blank=True, db_column='uuid_cole', primary_key=True, serialize=False)),
                ('colegio', models.TextField(blank=True, null=True)),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('zona_horaria', models.TextField(blank=True, null=True)),
                ('sexo_colegio', models.TextField(blank=True, db_column='sexo-colegio', null=True)),
                ('zoho_link', models.TextField(blank=True, db_column='zoho_link_', null=True)),
            ],
            options={
                'db_table': 'cole_tabla',
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_mol', models.TextField(blank=True, db_column='id_mol', primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulos',
            },
        ),
        migrations.CreateModel(
            name='MonitorTabla',
            fields=[
                ('uuid_mont', models.TextField(blank=True, db_column='uuid_mont', primary_key=True, serialize=False)),
                ('monitor', models.TextField(blank=True, null=True)),
                ('materia_feme', models.TextField(blank=True, null=True)),
                ('field_puntaje', models.FloatField(blank=True, db_column='per_puntaje', null=True)),
                ('whatsapp', models.FloatField(blank=True, null=True)),
                ('email_m', models.TextField(blank=True, null=True)),
                ('id_thinki_mon', models.FloatField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('uuid_cole', models.ForeignKey(db_column='uuid_cole', on_delete=django.db.models.deletion.CASCADE, to='core.coletabla')),
            ],
            options={
                'db_table': 'monitor_tabla',
            },
        ),
        migrations.CreateModel(
            name='MonitorTablaBeta',
            fields=[
                ('uuid_cole', models.TextField(blank=True, null=True)),
                ('uuid_mont', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('monitor', models.TextField(blank=True, null=True)),
                ('materia_feme', models.TextField(blank=True, null=True)),
                ('field_puntaje', models.FloatField(blank=True, db_column='per_puntaje', null=True)),
                ('whatsapp', models.FloatField(blank=True, null=True)),
                ('email_m', models.TextField(blank=True, null=True)),
                ('id_thinki_mon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monitor_tabla_beta',
            },
        ),
        migrations.CreateModel(
            name='SalonTablaBeta',
            fields=[
                ('uuid_salon', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('cierre_definitivo', models.TextField(blank=True, db_column='Cierre definitivo', null=True)),
                ('l3_22_23', models.TextField(blank=True, db_column='l3-22-23', null=True)),
                ('l3_22_23_2', models.TextField(blank=True, db_column='l3-22-23_2', null=True)),
                ('l3_22_23_au', models.TextField(blank=True, db_column='l3-22-23_au', null=True)),
                ('id_monitor', models.ForeignKey(db_column='uuid_mont', on_delete=django.db.models.deletion.CASCADE, to='core.monitortablabeta')),
            ],
            options={
                'db_table': 'salon_tabla_beta',
            },
        ),
        migrations.CreateModel(
            name='SalonTabla',
            fields=[
                ('uuid_salon', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('cierre_definitivo', models.TextField(blank=True, db_column='Cierre definitivo', null=True)),
                ('l3_22_23', models.TextField(blank=True, db_column='l3-22-23', null=True)),
                ('l3_22_23_2', models.TextField(blank=True, db_column='l3-22-23_2', null=True)),
                ('l3_22_23_au', models.TextField(blank=True, db_column='l3-22-23_au', null=True)),
                ('id_monitor', models.ForeignKey(db_column='uuid_mont', on_delete=django.db.models.deletion.CASCADE, to='core.monitortabla')),
            ],
            options={
                'db_table': 'salon_tabla',
            },
        ),
        migrations.CreateModel(
            name='SalonKpiModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.TextField(blank=True, null=True)),
                ('seccion', models.TextField(blank=True, null=True)),
                ('modulos', models.TextField(blank=True, null=True)),
                ('total_estudiantes', models.IntegerField(blank=True, null=True)),
                ('iniciaron', models.IntegerField(blank=True, null=True)),
                ('llevan50', models.IntegerField(blank=True, db_column='llevan_50', null=True)),
                ('completaron', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id_mol', models.ForeignKey(db_column='id_mol', on_delete=django.db.models.deletion.CASCADE, to='core.modulos')),
                ('uuid_salon', models.ForeignKey(db_column='uuid_salon', on_delete=django.db.models.deletion.CASCADE, to='core.salontabla')),
            ],
            options={
                'db_table': 'salon_kpi_modulo',
            },
        ),
        migrations.CreateModel(
            name='QuizTabla',
            fields=[
                ('id_pregunta', models.TextField(blank=True, db_column='id_pregunta', primary_key=True, serialize=False)),
                ('quiz', models.IntegerField(blank=True, null=True)),
                ('seccion', models.IntegerField(blank=True, null=True)),
                ('titulo_de_seccion', models.TextField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('tipo_de_pregunta', models.TextField(blank=True, null=True)),
                ('pregunta', models.TextField(blank=True, null=True)),
                ('respuesta_correcta', models.TextField(blank=True, null=True)),
                ('respuesta_incorrecta_1', models.TextField(blank=True, null=True)),
                ('respuesta_incorrecta_2', models.TextField(blank=True, null=True)),
                ('respuesta_incorrecta_3', models.TextField(blank=True, null=True)),
                ('respuesta_incorrecta_4', models.TextField(blank=True, null=True)),
                ('explicacion_de_la_respueta_correcta', models.TextField(blank=True, null=True)),
                ('id_mol', models.ForeignKey(db_column='id_mol', on_delete=django.db.models.deletion.CASCADE, to='core.modulos')),
            ],
            options={
                'db_table': 'quiz_tabla',
            },
        ),
        migrations.CreateModel(
            name='EstudiantesTabla',
            fields=[
                ('id_thinkific', models.TextField(blank=True, db_column='id_thinkific', primary_key=True, serialize=False)),
                ('uuid_mont', models.TextField(blank=True, null=True)),
                ('uuid_salon', models.TextField(blank=True, null=True)),
                ('colegio', models.TextField(blank=True, null=True)),
                ('grado', models.TextField(blank=True, null=True)),
                ('seccion', models.TextField(blank=True, null=True)),
                ('nombres_estudiantes', models.TextField(blank=True, null=True)),
                ('apellidos_estudiantes', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('whatsapp_estudiante', models.IntegerField(blank=True, null=True)),
                ('nombres_representante', models.TextField(blank=True, null=True)),
                ('apellidos_representante', models.TextField(blank=True, null=True)),
                ('whatsapp_responsable', models.IntegerField(blank=True, null=True)),
                ('email_representante', models.TextField(blank=True, null=True)),
                ('inscrito', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid_cole', models.ForeignKey(db_column='uuid_cole', on_delete=django.db.models.deletion.CASCADE, to='core.coletabla')),
            ],
            options={
                'db_table': 'estudiantes_tabla',
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, db_column='email', null=True)),
                ('started_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField()),
                ('expirated_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('per_completation', models.IntegerField(blank=True, null=True)),
                ('per_videos', models.IntegerField(blank=True, null=True)),
                ('estatus', models.TextField(blank=True, db_column='estatus', null=True)),
                ('created_at', models.DateTimeField()),
                ('last_sign_in', models.DateTimeField()),
                ('nota_quiz1', models.DecimalField(decimal_places=2, max_digits=16)),
                ('nota_quiz2', models.DecimalField(decimal_places=2, max_digits=16)),
                ('nota_quiz3', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fecha_q1', models.DateTimeField()),
                ('fecha_q2', models.DateTimeField()),
                ('fecha_q3', models.DateTimeField()),
                ('nota_quizes', models.DecimalField(decimal_places=2, max_digits=16)),
                ('nota_progreso', models.DecimalField(decimal_places=2, max_digits=16)),
                ('nota_total', models.IntegerField(blank=True, null=True)),
                ('nota_total_l', models.TextField(blank=True, db_column='nota_total_l', null=True)),
                ('id_thinkific', models.ForeignKey(db_column='id_thinkific', on_delete=django.db.models.deletion.CASCADE, to='core.estudiantestabla')),
            ],
            options={
                'db_table': 'estatus',
            },
        ),
    ]
