# Generated by Django 4.2 on 2023-04-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitortabla',
            name='key',
        ),
        migrations.AddField(
            model_name='monitortabla',
            name='userToken',
            field=models.CharField(blank=True, db_column='userToken', max_length=100, null=True, unique=True),
        ),
    ]
