# Generated by Django 4.2 on 2023-07-13 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatusthinkific',
            name='email',
        ),
        migrations.AlterField(
            model_name='contenidoscolegio',
            name='lapso',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='estatusthinkific',
            name='activated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estatusthinkific',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estatusthinkific',
            name='expirated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estatusthinkific',
            name='fecha_q1',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estatusthinkific',
            name='fecha_q2',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estatusthinkific',
            name='fecha_q3',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estatusthinkific',
            name='last_sign_in',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estatusthinkific',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estatusvalu',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estatusvalu',
            name='fecha_q1',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estatusvalu',
            name='fecha_q2',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estatusvalu',
            name='fecha_q3',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estatusvalu',
            name='intento_quiz1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estatusvalu',
            name='intento_quiz2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estatusvalu',
            name='intento_quiz3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='whatsapp',
            field=models.IntegerField(null=True),
        ),
    ]
