# Generated by Django 4.2 on 2023-04-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coletabla_sexo_colegio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulos',
            name='id_mol',
            field=models.TextField(blank=True, db_column='id_mol', primary_key=True, serialize=False),
        ),
    ]
