# Generated by Django 4.2 on 2023-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coletabla_sexo_colegio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salontabla',
            name='l3_22_23',
            field=models.TextField(blank=True, db_column='l3_22_23', null=True),
        ),
        migrations.AlterField(
            model_name='salontabla',
            name='l3_22_23_2',
            field=models.TextField(blank=True, db_column='l3_22_23_2', null=True),
        ),
        migrations.AlterField(
            model_name='salontabla',
            name='l3_22_23_au',
            field=models.TextField(blank=True, db_column='l3_22_23_au', null=True),
        ),
    ]
