# Generated by Django 4.2 on 2023-06-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_salontabla_l3_22_23_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonkpimodulo',
            name='total_estudiante',
        ),
        migrations.AddField(
            model_name='salonkpimodulo',
            name='total_estudiantes',
            field=models.IntegerField(blank=True, db_column='total_estudiantes', null=True),
        ),
    ]
