# Generated by Django 4.2 on 2023-04-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_modulos_id_mol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantestabla',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
