# Generated by Django 4.2 on 2023-04-20 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_estudiantestabla_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonKpiModuloBeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.TextField(blank=True, null=True)),
                ('seccion', models.TextField(blank=True, null=True)),
                ('modulos', models.TextField(blank=True, null=True)),
                ('total_estudiantes', models.IntegerField(blank=True, null=True)),
                ('iniciaron', models.IntegerField(blank=True, null=True)),
                ('llevan50', models.IntegerField(blank=True, db_column='llevan_+50%', null=True)),
                ('completaron', models.IntegerField(blank=True, null=True)),
                ('id_mol', models.ForeignKey(db_column='id_mol', on_delete=django.db.models.deletion.CASCADE, to='core.modulos')),
                ('uuid_salon', models.ForeignKey(db_column='uuid_salon', on_delete=django.db.models.deletion.CASCADE, to='core.salontabla')),
            ],
            options={
                'db_table': 'salon_kpi_modulo_beta',
            },
        ),
    ]
