# Generated by Django 4.2 on 2023-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_salonkpimodulobeta2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonkpimodulobeta2',
            name='llevan50',
        ),
        migrations.AddField(
            model_name='salonkpimodulobeta2',
            name='llevan',
            field=models.IntegerField(blank=True, db_column='llevan', null=True),
        ),
    ]
