# Generated by Django 4.2 on 2023-04-21 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_salonkpimodulobeta2_llevan50_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonkpimodulobeta2',
            name='llevan',
        ),
        migrations.AddField(
            model_name='salonkpimodulobeta2',
            name='llevan50',
            field=models.IntegerField(blank=True, db_column='llevan_+50%', null=True),
        ),
        migrations.CreateModel(
            name='SalonKpiModuloBeta3',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('grado', models.TextField(blank=True, null=True)),
                ('seccion', models.TextField(blank=True, null=True)),
                ('modulos', models.TextField(blank=True, null=True)),
                ('total_estudiantes', models.IntegerField(blank=True, null=True)),
                ('iniciaron', models.IntegerField(blank=True, null=True)),
                ('llevan', models.IntegerField(blank=True, db_column='llevan', null=True)),
                ('completaron', models.IntegerField(blank=True, null=True)),
                ('id_mol', models.ForeignKey(db_column='id_mol', on_delete=django.db.models.deletion.CASCADE, to='core.modulos')),
                ('uuid_salon', models.ForeignKey(db_column='uuid_salon', on_delete=django.db.models.deletion.CASCADE, to='core.salontabla')),
            ],
            options={
                'db_table': 'salon_kpi_modulo_beta_3',
            },
        ),
    ]
