name: Deploy to GCP Compute Engine

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$GCP_SSH_KEY" > ~/.ssh/google_compute_engine
          echo "$GCP_PUBLIC_SSH_KEY" > ~/.ssh/google_compute_engine.pub
          chmod 600 ~/.ssh/google_compute_engine
          chmod 600 ~/.ssh/google_compute_engine.pub
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Set up GCP CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
      
      - name: Deploy to Compute Engine
        run: |
          gcloud compute scp --recurse . django-vm-vm --zone southamerica-east1-a
#         gcloud compute instances update django-vm-vm --zone southamerica-east1-a --source .
